# Generated by Django 2.0 on 2017-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=50)),
                ('startQuantity', models.IntegerField()),
                ('customers', models.ManyToManyField(to='auth.Group')),
                ('productClasses', models.ManyToManyField(to='shop.ProductClass')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'verbose_name': 'Sale',
                'ordering': ['sale', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SaleSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=50)),
                ('startSum', models.DecimalField(decimal_places=2, max_digits=50)),
                ('customers', models.ManyToManyField(to='auth.Group')),
                ('productClasses', models.ManyToManyField(to='shop.ProductClass')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'verbose_name': 'Sale',
                'ordering': ['sale', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='productClasses',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
