# Generated by Django 2.0 on 2018-01-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default='2018-01-01 00:00'),
        ),
    ]
