# Generated by Django 2.0 on 2018-01-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180101_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Organisation'),
        ),
    ]
