# Generated by Django 2.0 on 2018-01-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180103_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='organisation',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='organisation',
            name='bik',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='checkingAccount',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='organisation',
            name='corAccount',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='organisation',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
