# Generated by Django 2.0 on 2018-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180104_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='bik',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='checkingAccount',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='corAccount',
        ),
        migrations.AddField(
            model_name='invoce',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='invoce',
            name='bik',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoce',
            name='checkingAccount',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='invoce',
            name='corAccount',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
