# Generated by Django 2.0 on 2018-01-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180105_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoce',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='invoce',
            name='bik',
        ),
        migrations.RemoveField(
            model_name='invoce',
            name='checkingAccount',
        ),
        migrations.RemoveField(
            model_name='invoce',
            name='corAccount',
        ),
        migrations.AddField(
            model_name='invoce',
            name='personInCharge',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
