# Generated by Django 2.0 on 2018-01-14 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_auto_20180105_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, default='', max_length=20)),
                ('kpp', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('bik', models.CharField(blank=True, default='', max_length=50)),
                ('corAcc', models.CharField(blank=True, default='', max_length=250)),
                ('bank', models.CharField(blank=True, default='', max_length=250)),
                ('checkACC', models.CharField(blank=True, default='', max_length=50)),
                ('owners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organisations',
                'ordering': ['inn'],
                'verbose_name': 'Organisation',
            },
        ),
        migrations.AlterField(
            model_name='invoce',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.SellerOrganisation'),
        ),
    ]
