# Generated by Django 2.0 on 2018-01-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180114_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerorganisation',
            options={'ordering': ['inn'], 'verbose_name': 'SellerOrganisation', 'verbose_name_plural': 'SellerOrganisations'},
        ),
    ]
