# Generated by Django 2.0 on 2018-01-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180114_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='measure',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
