# Generated by Django 2.0 on 2018-01-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180115_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='productVar',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductVariant'),
        ),
    ]
