# Generated by Django 2.0 on 2018-01-18 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20180117_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 18, 17, 58, 33, 625933, tzinfo=utc)),
        ),
    ]
