# Generated by Django 2.0 on 2018-01-21 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180118_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='measure',
        ),
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, default='шт', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 21, 12, 44, 0, 588226, tzinfo=utc)),
        ),
    ]
