# Generated by Django 2.0 on 2018-01-25 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20180121_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipAddress',
        ),
        migrations.AddField(
            model_name='invoce',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoce',
            name='shipAddress',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 25, 14, 56, 48, 454392, tzinfo=utc)),
        ),
    ]
