# Generated by Django 2.0 on 2018-01-25 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20180125_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 25, 15, 6, 39, 680630, tzinfo=utc)),
        ),
    ]
