# Generated by Django 2.0 on 2018-01-25 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20180125_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoce',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 25, 18, 32, 58, 327242, tzinfo=utc)),
        ),
    ]
