# Generated by Django 2.0 on 2018-02-01 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20180125_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='vendorCode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 1, 17, 4, 6, 314662, tzinfo=utc)),
        ),
    ]
