# Generated by Django 2.0 on 2018-02-01 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20180201_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 1, 17, 26, 16, 373713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='vendorCode',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
