# Generated by Django 2.0 on 2018-02-02 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20180201_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 2, 7, 15, 12, 194803, tzinfo=utc)),
        ),
    ]
