# Generated by Django 2.0 on 2018-02-04 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20180202_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 4, 18, 9, 54, 807542, tzinfo=utc)),
        ),
    ]
