# Generated by Django 2.0 on 2018-02-11 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20180204_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 11, 14, 13, 42, 116579, tzinfo=utc)),
        ),
    ]
