# Generated by Django 2.0 on 2018-02-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20180211_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoce',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, default='2018-01-01 00:00'),
        ),
    ]
