# Generated by Django 2.0 on 2018-02-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20180211_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoce',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.Order'),
        ),
    ]
