# Generated by Django 2.0 on 2018-02-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20180211_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoce',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='invoce',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.Invoce'),
        ),
    ]
