# Generated by Django 2.0.2 on 2018-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20180211_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoce',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
